# Generated by Django 4.0 on 2022-01-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
