# Generated by Django 3.2.7 on 2022-01-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0002_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bio',
        ),
    ]
