# Generated by Django 3.2.7 on 2022-01-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0003_delete_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign',
        ),
    ]
